### ISSUE TITLE
How to set en exact minimum value for spectrum display mode?

### ISSUE THREAD

**Issue by yamac-kurtulus** [flant/grafana-statusmap#132]
Hello, first of all, I believe you have filled some very major gap in grafana with your plug in. Kudos to that. 

I am using statusmap in spectrum mode to view some continuous values of services between 0-1. In the spectrum mode, I want to see red for 0, and 1 for green and the gradient for everything in between. When everything is green (1) and some value changes to, say, 0.88, then the spectrum is fitted to 0.88-1 Lowest value becomes red, and the legend shows the colors of 0.88-1.0 range. Is there a way to tell the plugin to assume lowest value to be 0? 

Note: I tried setting min and max values of color scale in color section. 
![image](https://user-images.githubusercontent.com/32689837/93001427-89ac5380-f537-11ea-806a-d2bf22720a33.png)

**Comment by diafour** [comment]
Hello! Thank you for your kind words!

This problem is definitely a bug as stated in https://github.com/flant/grafana-statusmap/issues/124.

The idea of `min value` and `max value` inputs is borrowed from standard heatmap-panel: values from the datasource are clamped to the range of min and max. No additional UI switch is required, the `restrict` flag from PR#134 should be on if there is something in `min` and/or `max` inputs. 

I've planned to fix this problem and add tests by the end of the month. However, feel free to rework your PR, it is great to see new contributors!

**Comment by yamac-kurtulus** [comment]
I thought this was a use case so I wanted to include a switch.

Any way, I have just updated #134. I did not want to merge #132 (solving #124) to this one because it might not be the right way to do it.
