### ISSUE TITLE
[Feature Request] Flux - Add trim on ${__y_label} when building tooltip link due to dummy blank space in YLabel

### ISSUE THREAD

**Issue by sbengo** [flant/grafana-statusmap#147]
Hi @diafour ,

First of all, thanks for this awesome panel!
We are using it to show discrete results based on status result (0,1,2,...) using InfluxDB as datasource (1.8.2)
We need to improve the logic of this status, so we are going to migrate the InfluxDB queries (IQL) to Flux. We don't have the Grafana 7 yet, so we are still using the Flux datasource (deprecated):

- Grafana: 6.6.3
- StatusMap Panel: 0.3.4
- Flux Datasource (BETA): 5.4.1

We have managed to create our queries on Flux, but as we have seen, the generated `YLabel` adds a dummy blank space.
It breaks the link generation, as we are using the `YLabel` to create the link and it is adding this blank space.

So:
I will address a PR to add a new variable: `__y_label__trimm` that will trim (.trim()) the YLabel value to ensure that no trimming blank space is added into the label

Example:

Data returned by Flux - no blank space is added - note that _field is being propagated as the YLabel
```haskell
#default,_result,,,,
,result,table,_field,_time,_value
,,0,webrobot-chome-79,2020-11-26T07:05:00Z,0
,,0,webrobot-chome-79-2,2020-11-26T07:10:00Z,0
```
On the StatusMap, the generated `YLabel` is directly the `_field` with the blank space:

```haskell
> console.log(this.targets)
[" webrobot-chome-79", " webrobot-chome-79-2"]
0: " webrobot-chome-79"
1: " webrobot-chome-79-2"
```

Thanks,
Regards!

**Comment by diafour** [comment]
Hello! Thank you for your PR and your time.

My first intention was that the [problem](https://github.com/grafana/influxdb-flux-datasource/blob/v5.4.1/src/response_parser.ts#L30-L39) in _one_ _deprecated_ datasource plugin is fixed by introducing the new feature in the panel plugin. But after some time I've come to the use case for all datasources.  `__y_label_trim` can be useful when the "Alias" contains multiple variables delimited by space and the leading variable is empty, so `target` will contain leading spaces. For example: if alias is `${group_name} ${server_name}` and the datasource returns empty group then "__y_label" value becomes " server-name-10".

So, I'll merge this feature.

P.S. No estimated release date though, because of recent changes in plugin publishing process.
