### ISSUE TITLE
Add ability to split panel result by pages

### ISSUE THREAD

**Issue by Yzzzi** [flant/grafana-statusmap#83]
We are using your panel to show our pull requests status in time and its working great. Number of pull requests dynamicly changes, and sometimes there are so much of them that panel becomes unreadable. So it would be great to add ability to split rows to different pages when its too many of them like its done on grafana table panel.

**Comment by diafour** [comment]
@JoaquinJimenezGarcia has uploaded some previews of this feature! (See https://github.com/flant/grafana-statusmap/pull/91#issue-383654354)

![pagination_page1](https://user-images.githubusercontent.com/10835286/75896472-6fcadf00-5e37-11ea-9001-ced4fdf2fe35.png)
![pagination_page2](https://user-images.githubusercontent.com/10835286/75896478-722d3900-5e37-11ea-912e-d686524678d9.png)
![pagination_options](https://user-images.githubusercontent.com/10835286/75896487-75282980-5e37-11ea-85d3-0fff27fc81a7.png)

Let's discuss it here

**Comment by diafour** [comment]
1. Settings editor. I think that "Pagination options" section can be removed and "Paginate elements" switch can be placed in a "Display" section and labeled as "Pagination". ("Display" section transforms into a separate tab in the future.)

2. What is the "Panel ID"?

3. New elements on the panel: "Items per page" input, "Showing A to B of N entries" label and "Prev/Next" buttons. These elements are spread all over the panel — it doesn't look great. I suggest to place them together in the bottom left corner and move the legend to the right:
![pagination-suggest-1](https://user-images.githubusercontent.com/1055474/75902092-90ebf980-5e50-11ea-9497-892404426d5f.png)

If the legend is turned off, pagination elements can be placed in one row:
![pagination-suggest-2](https://user-images.githubusercontent.com/1055474/75902355-ede7af80-5e50-11ea-941c-2ad27e50ca55.png)

**Comment by JoaquinJimenezGarcia** [comment]
I can make all the visual changes you propose (points 1 and 3).

Sorry for not describing the Panel ID before. It's an identifier (not unique) that allows the user to choose the number of elements per page and the page wanted to see by the url (i.e. pgsize_hola=5&pgcurrent_hola=1&pgsize_adios=25&pgcurrent_adios=5 -> it will set the page size from "hola" panel to 5 and going to the first page, also it will set the page size of "adios" panel to 25 and going to the fifth page). So you can have multiple statusmap in a dashboard and managing them from the URL.

Regarding the subject about replacing "Items per page" for "Row minimal height", I have been talking with some members of my teams and some clients that use it, and they, as users, prefers to select the items per page (because they just want to see items) instead of selecting the row height. Nevertheless, if you think this is very important I could include it as well, but it could take some days.

**Comment by diafour** [comment]
> I can make all the visual changes you propose (points 1 and 3).

Great!

> Panel ID

OK. It seems interesting. Can you move this input under the "Pagination" switch and make it disabled if pagination is disabled?

>  "Row minimal height"

It is not important, "Items per page" is good. "Row minimal height" is a separate option that can be used to automatically set "Items per page" based on a graph height. It is also useful without pagination, I think this can be implemented later.

**Comment by JoaquinJimenezGarcia** [comment]
Hi @diafour !

This feature is done. I'm making a new PR. Also, I fixed the problem with the second tooltip mentioned here #92

**Comment by diafour** [comment]
The feature is released in 0.3.0. Thank you, @JoaquinJimenezGarcia .

**Comment by retr0h** [comment]
> The feature is released in 0.3.0. Thank you, @JoaquinJimenezGarcia .

@diafour Can you release this [upstream](https://grafana.com/grafana/plugins/natel-discrete-panel)?  Looks like we are still at `0.1.0` ?

**Comment by diafour** [comment]
@retr0h `natel-discrete-panel` is another plugin. The latest version of flant-statusmap-panel is 0.3.1, PR to Grafana repository is here: https://github.com/grafana/grafana-plugin-repository/pull/680
