### ISSUE TITLE
Extra links tooltip and Pagination 

### ISSUE THREAD

**Issue by JoaquinJimenezGarcia** [flant/grafana-statusmap#84]
Hello!

My name is Joaquín Jiménez and I work for an IT company. As part of our product, we offer to our clients services based in Grafana.

Some time ago we started using your plugin as a crutial part of our service. And due to that, we have developed some possible enhancements we would really love to include as part of your plugin. 

Those are:

- Extra links tooltip: when the mouse hover a field with a value, it will create a tooltip with some extra links (i.e. navigating to another window, download a resource...)

![image](https://user-images.githubusercontent.com/10835286/71896000-d80c8580-3152-11ea-98aa-d92bbe1f3add.png)

- Pagination: we have realized that when you have many different values, the font size gets smaller and smaller, getting it difficult to see. As a solution, we propose a way to paginate all the values.

![image (1)](https://user-images.githubusercontent.com/10835286/71896020-e3f84780-3152-11ea-9663-cb8d778241df.png)

Thank you very much in advance!!

**Comment by diafour** [comment]
Hello, Joaquín! Thank you for your kind words. It is very interesting to see new cases of production usage!

"Extra links in a tooltip" is a great feature and it was requested a time ago in #17. Feel free to make a PR and resume a discussion there.

Pagination was also requested, see #83. We have discussed it internally and it seems a more «invasive» enhancement and a complicated one because of plans to make a hierarchical Y-axis (see #26). It will be great if you send more screenshots and a description to start a public discussion in #83.

**Comment by diafour** [comment]
PRs are merged and released as 0.3.0
